---
title: "R Notebook"
output: html_notebook
---

Packages
```{r}
install.packages("haven", "ggplot2", "dplyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("tidyverse")
library(haven)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tidyverse)
```

Import ADAE
```{r}

adae <- read_sas("https://github.com/elong0527/r4csr/raw/master/data-adam/adae.sas7bdat", 
    NULL)
```

Import ADSL
```{r}
adsl <- read_sas("https://github.com/elong0527/r4csr/raw/master/data-adam/adsl.sas7bdat", 
    NULL)
```

ggplot2
```{r}
ggplot2(adae) +
  aes(x = TRTA, y = AEBODSYS, fill = AESEV) +
  geom_tile(size = 1.2) +
  scale_fill_hue(direction = 1) +
  theme_minimal()



```

ggplot(ggplot2::economics) +
  aes(x = date, y = pce, fill = psavert) +
  geom_line(size = 0.5, colour = "#112446") +
  scale_fill_gradient() +
  theme_minimal()

functions
```{r}
fmt_num <- function(x, digits, width = digits + 4) {
  formatC(x,
    digits = digits,
    format = "f",
    width = width
  )
}
```


Prep Data
```{r}
pop <- adsl %>%
  filter(SAFFL == "Y") %>%
  rename(TRTAN = TRT01AN) %>%
  count(TRTAN, name = "tot")

tidy_ae <- adae %>%
  mutate(
    all = SAFFL == "Y",
    drug = AEREL %in% c("POSSIBLE", "PROBABLE"),
    ser = AESER == "Y",
    drug_ser = drug & ser,
    die = AEOUT == "FATAL"
  ) %>%
  select(USUBJID, TRTAN, all, drug, ser, drug_ser, die) %>%
  pivot_longer(cols = c(all, drug, ser, drug_ser, die))

```


Table

```{r}
ana <- tidy_ae %>%
  filter(value == TRUE) %>%
  group_by(TRTAN, name) %>%
  summarise(n = n_distinct(USUBJID)) %>%
  left_join(pop, by = "TRTAN") %>%
  mutate(
    pct = fmt_num(n / tot * 100, digits = 1),
    n = fmt_num(n, digits = 0),
    pct = paste0("(", pct, ")")
  )

```
